import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "./Provider";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "@components/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es">
			<body className={inter.className}>
				<AuthProvider>
					<Provider>{children}</Provider>
				</AuthProvider>
			</body>
		</html>
	);
}
